name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ master ]

jobs:
  publish:
    name: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [14, 16]
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: install nodejs
        uses: actions/setup-node@v3.0.0
        with:
          node-version: ${{ matrix.node }}

      - name: install dependencies
        run: yarn install --production false --frozen-lockfile

      - name: lint
        run: yarn run lint

      - name: test
        run: yarn run test:ci

      - name: build
        run: yarn run build
